#!/usr/bin/env python

import argparse
import asyncio

import grpc
from yarl import URL

from lib import chirpstack


def get_grpc_channel(host: str, port: str, secure: bool = True, cert_path: str = None):
    target_addr = f"{host}:{port}"
    channel = None

    if secure:
        if cert_path is not None:
            with open(cert_path, "rb") as f:
                credentials = grpc.ssl_channel_credentials(f.read())
        else:
            credentials = grpc.ssl_channel_credentials()

        channel = grpc.aio.secure_channel(target_addr, credentials)
    else:
        channel = grpc.aio.insecure_channel(target_addr)

    return channel


async def get_or_create_ns(chirpstack_api: chirpstack.ChirpStackAPI, name, server):
    async for network_server in chirpstack_api.get_network_servers(None):
        if network_server.server.lower() == server.lower():
            return network_server.id
    return await chirpstack_api.create_network_server(name=name, server=server)


async def main():
    parser = argparse.ArgumentParser(formatter_class=argparse.ArgumentDefaultsHelpFormatter)
    parser.add_argument("--username", type=str, help="Username", default="admin", required=False)
    parser.add_argument("--password", type=str, help="Password", default="admin", required=False)
    parser.add_argument("--gateway-id", help="Gateway id (mac)", default="000000000000C0DE", required=False)
    parser.add_argument("--name", type=str, help="Gateway unique name", default="chirpstack-ran-bridge", required=False)
    parser.add_argument(
        "--description", type=str, help="Gateway description", default="ChirpStack RAN gateway", required=False
    )
    parser.add_argument("--ns-name", type=str, help="Network server name", default="chirpstack")
    parser.add_argument(
        "--recreate",
        action="store_true",
        help="Force to delete and create new gateway if it already exists",
        default=False,
    )
    parser.add_argument("--ns-addr", type=str, help="Network server address", default="chirpstack-network-server:8000")
    parser.add_argument(
        "--organization-id", type=int, help="Id for organization-owner of created gateway", default=None
    )
    parser.add_argument(
        "--as-addr",
        type=str,
        help="ChirpStack application server URL",
        default="http://chirpstack-application-server:8080",
        required=False,
    )
    args = parser.parse_args()

    chirpstack_internal_api = chirpstack.ChirpStackInternalAPI(args.as_addr, args.username, args.password)
    await chirpstack_internal_api.authenticate()

    url = URL(args.as_addr)
    grpc_channel = get_grpc_channel(url.host, url.port, url.scheme == "https")
    chirpstack_api = chirpstack.ChirpStackAPI(grpc_channel, chirpstack_internal_api._jwt_token)

    existed_gateway = await chirpstack_api.get_gateway(args.gateway_id)
    if existed_gateway:
        if args.recreate:
            print("Recreating gateway...\n")
            await chirpstack_api.delete_gateway(existed_gateway.gateway.id)
        else:
            print(
                f"Gateway with id {existed_gateway.gateway.id!r} already exist! "
                "If you want to recreate gateway pass '--recreate' parameter.\n"
            )
            print(f'CHIRPSTACK_GATEWAY_ID="{existed_gateway.gateway.id}"')
            return

    organization_id = args.organization_id
    if organization_id is None:
        user_profile = await chirpstack_internal_api.profile()
        organization_id = int(user_profile["organizations"][0]["organizationID"])

    print(organization_id)

    network_server_id = await get_or_create_ns(chirpstack_api, args.ns_name, args.ns_addr)
    service_profile_id = await chirpstack_api.create_service_profile(
        name="chirpstack-ran-service-profile", organization_id=organization_id, network_server_id=network_server_id
    )
    await chirpstack_api.create_gateway(
        args.gateway_id,
        "gw-" + args.gateway_id,
        "Autogenerated gateway for RAN-bridge",
        network_server_id,
        organization_id=organization_id,
        service_profile_id=service_profile_id,
    )

    print(f'CHIRPSTACK_GATEWAY_ID="{args.gateway_id}"')


if __name__ == "__main__":
    asyncio.run(main())
